# PR Labeler configuration
# Refer to https://github.com/actions/labeler for usage

feature:
  - changed-files:
    - any-glob-to-any-file: 'src/features/**/*'

fix:
  - changed-files:
    - any-glob-to-any-file: 'src/utils/**/*'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/components/**/*'
      - 'src/styles/**/*'
      - '**/*.css'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'

chore:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - '.gitignore'
      - 'eslint.config.js'
      - 'tsconfig*.json'
      - 'vite.config.ts'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**/*'
